#theme: jekyll-theme-minimal
title: Loic Le Meur homepage
description: Bookmark this to keep an eye on my project updates!

plugins:
  - jekyll-relative-links
relative_links:
  enable: true
  collections: true
include:
  - README.md

# Build settings
markdown: kramdown

